export const EXPENSE_CATEGORIES = [
  'Rent',
  'Utilities',
  'Salaries',
  'Office Supplies',
  'Marketing',
  'Transportation',
  'Equipment',
  'Professional Services',
  'Insurance',
  'Miscellaneous',
];

export const INCOME_CATEGORIES = [
  'Sales',
  'Services',
  'Consulting',
  'Interest',
  'Other Income',
];

export function getMockTransactions() {
  return [
    {
      id: '1',
      type: 'income' as const,
      amount: 15000,
      description: 'Monthly sales revenue',
      category: 'Sales',
      date: '2025-10-01',
      createdBy: 'John Doe',
    },
    {
      id: '2',
      type: 'expense' as const,
      amount: 2500,
      description: 'Office rent payment',
      category: 'Rent',
      date: '2025-10-01',
      createdBy: 'John Doe',
    },
    {
      id: '3',
      type: 'expense' as const,
      amount: 3500,
      description: 'Employee salaries',
      category: 'Salaries',
      date: '2025-10-02',
      createdBy: 'John Doe',
    },
    {
      id: '4',
      type: 'income' as const,
      amount: 5000,
      description: 'Consulting project payment',
      category: 'Consulting',
      date: '2025-10-03',
      createdBy: 'John Doe',
    },
    {
      id: '5',
      type: 'expense' as const,
      amount: 450,
      description: 'Electricity and water bills',
      category: 'Utilities',
      date: '2025-10-03',
      createdBy: 'John Doe',
    },
    {
      id: '6',
      type: 'expense' as const,
      amount: 800,
      description: 'Marketing campaign - social media ads',
      category: 'Marketing',
      date: '2025-10-04',
      createdBy: 'John Doe',
    },
    {
      id: '7',
      type: 'income' as const,
      amount: 8000,
      description: 'Service contracts revenue',
      category: 'Services',
      date: '2025-10-05',
      createdBy: 'John Doe',
    },
    {
      id: '8',
      type: 'expense' as const,
      amount: 200,
      description: 'Office supplies purchase',
      category: 'Office Supplies',
      date: '2025-10-05',
      createdBy: 'John Doe',
    },
    {
      id: '9',
      type: 'expense' as const,
      amount: 150,
      description: 'Transportation and fuel',
      category: 'Transportation',
      date: '2025-10-06',
      createdBy: 'John Doe',
    },
    {
      id: '10',
      type: 'income' as const,
      amount: 3200,
      description: 'Product sales',
      category: 'Sales',
      date: '2025-10-07',
      createdBy: 'John Doe',
    },
    // Previous months data
    {
      id: '11',
      type: 'income' as const,
      amount: 12000,
      description: 'September sales revenue',
      category: 'Sales',
      date: '2025-09-15',
      createdBy: 'John Doe',
    },
    {
      id: '12',
      type: 'expense' as const,
      amount: 2500,
      description: 'September rent',
      category: 'Rent',
      date: '2025-09-01',
      createdBy: 'John Doe',
    },
    {
      id: '13',
      type: 'income' as const,
      amount: 14000,
      description: 'August sales revenue',
      category: 'Sales',
      date: '2025-08-20',
      createdBy: 'John Doe',
    },
    {
      id: '14',
      type: 'expense' as const,
      amount: 3200,
      description: 'August salaries',
      category: 'Salaries',
      date: '2025-08-01',
      createdBy: 'John Doe',
    },
    {
      id: '15',
      type: 'income' as const,
      amount: 13500,
      description: 'July sales revenue',
      category: 'Sales',
      date: '2025-07-25',
      createdBy: 'John Doe',
    },
  ];
}
